#!/usr/bin/env bash

#################
# Lib utilities
#################
NAME=BOOTSTRAPPER

function curtime () {
    date +'%H:%M:%S'
}
function log () {
    local append_newline=false
    if [ $1 = "-n" ]; then
        shift
        append_newline=true
    fi
    printf "@${NAME}($(curtime))[$1]: $2"
    [[ ${append_newline} = true ]] && printf "\n"
}
function confirm () {
    while true; do
        read -e -p "@${NAME}($(curtime))[PROMPT]: $1 [YyNn] " -n 1 -r
        case ${REPLY} in
            [Yy])
                return 0;;
            [Nn])
                return 1;;
            *)
                log -n ERROR "Please answer Y or N";;
        esac
    done
}
function query () {
    read -p "@${NAME}($(curtime))[PROMPT]: $1 " -r
    echo ${REPLY}
}

function install_from_list () {
    local input_type=$1         # Name of the input type; e.g. "packages"
    local installer=$2          # Installer prefix; e.g. "brew install"
    local checker=$3            # Checker prefix; e.g. "brew list"
    local packages=( ${@:4} )   # Input list; e.g. "(neofetch nethack)"

    log INFO "Checking ${input_type}.."
    declare -a missing_packages
    for package in "${packages[@]}"; do
        echo -n "."
        if ! eval ${checker} ${package} >/dev/null 2>&1; then
            missing_packages+=(${package})
        fi
    done
    echo
    num_missing=${#missing_packages[@]}
    if [[ ${num_missing} -gt 0 ]]; then
        log -n INFO "The following ${input_type} are missing: ${missing_packages[*]}"
        if [[ ${num_missing} -gt 1 ]] && confirm "Install all ${input_type}?"; then
            eval ${installer} ${missing_packages[@]}
        else
            for package in "${missing_packages[@]}"; do
                if confirm "Install \"${package}\"?"; then
                    eval ${installer} ${package}
                fi
            done
        fi
    else
        log -n INFO "No missing ${input_type}"
    fi
    unset missing_packages
}

#################
# Initializer
#################

cd ${HOME}
case $(uname -s) in
    *Darwin*)
        log -n INFO "Starting bootstrap for MacOS"
        system_type='Darwin'
        ;;
    *)
        log -n ERROR "Unsupported OS"
        exit 1
        ;;
esac

#################
# MacOS
#################
if [ "${system_type}" = "Darwin" ]; then
    casks=(
        docker
        dropbox
        kitty
        mpv
        vnc-viewer
    )
    packages=(
        dict
        fd
        fzf
        ghostscript
        git-delta
        httpie
        imagemagick
        neofetch
        neovim
        npm
        python-tk
        ripgrep
        texlive
        yadm
    )

    if ! command -v brew >/dev/null 2>&1; then
        log -n INFO "Installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    install_from_list \
        "casks" \
        "brew install --cask" \
        "brew list --cask" \
        "${casks[@]}"
    install_from_list \
        "packages" \
        "brew install" \
        "brew list" \
        "${packages[@]}"

    # Git Manager
    if ! brew tap | grep microsoft/git >/dev/null 2>&1 && confirm "Install Github Manager?"; then
        brew tap microsoft/git
        brew install --cask git-credential-manager-core
    fi
    # Fonts
    if ! brew tap | grep cask-fonts >/dev/null 2>&1 && confirm "Install fonts?"; then
        brew tap homebrew/cask-fonts
        brew install --cask font-hack-nerd-font
    fi

fi

#################
# Post-Install
#################

# YADM
if ! command -v yadm >/dev/null 2>&1; then
    log -n ERROR "YADM is required to proceed; please install YADM"
    exit 1
elif ! $(yadm list >/dev/null 2>&1); then
    log -n INFO "Initializing YADM"
    yadm clone "https://github.com/vmizener/dots.git"
fi

# Python
if command -v python3 >/dev/null 2>&1 && confirm "Update Python3?"; then
    log -n INFO "Installing Python packages"
    pip3 install -r .config/yadm/requirements.txt --user
    log -n INFO "Updating Pip"
    pip3 install --upgrade pip --user
fi

# NPM
if command -v npm >/dev/null 2>&1 && confirm "Update NPM?"; then
    log -n INFO "Updating NPM"
    npm install -g npm
    node_packages=(
        json-server # Deploy a fake REST API server
        pyright     # Python language server
    )
    install_from_list \
        "NPM packages" \
        "npm install -g" \
        "npm list -g --depth 0" \
        "${node_packages[@]}"
else
    log -n WARNING "NPM is not installed; some packages will be missing"
fi

# Neovim
if command -v nvim >/dev/null 2>&1 && confirm "Bootstrap Neovim?"; then
    log -n INFO "Updating Neovim"
    if [ ! -d ~/.local/share/nvim/site/pack/packer ]; then
        git clone https://github.com/wbthomason/packer.nvim \
             ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    fi
    # log -n INFO "Updating Neovim"
    # if [ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
    #     log INFO "Installing Vim-Plug"
    #     sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    #         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    # fi
    # log -n INFO "Updating Neovim plugins"
    nvim '+autocmd User PackerComplete sleep 100m | qall' +PackerSync
    # nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

#################
# Cleanup
#################

log -n INFO "Bootstrap completed successfully!"
