#!/usr/bin/env bash

#################
# Lib functions
#################

function log () {
    printf "@BOOTSTRAPPER[$1]: $2\n"
}
function query () {
    read -e -p "@BOOTSTRAPPER[PROMPT]: $1 [YyNn] " -n 1 -r
    if [[ ${REPLY} =~ ^[Yy]$ ]]; then
        exit 0
    elif [[ ${REPLY} =~ ^[Nn]$ ]]; then
        exit 1
    else
        log ERROR "Please answer Y or N";
	query $1
    fi
}
function prompt () {
    read -p "@BOOTSTRAPPER[PROMPT]: $1 " -r
    return ${REPLY}
}

#################
# Initializer
#################

cd ${HOME}
case $(uname -s) in
    *Darwin*)
        log INFO "Starting bootstrap for MacOS"
        system_type='Darwin'
        ;;
    *)
        log ERROR "Unsupported OS"
        exit 1
        ;;
esac

#################
# MacOS
#################
if [ "${system_type}" = "Darwin" ]; then
    PACKAGES=(
        yadm
    )

    if ! command -v brew >/dev/null 2>&1; then
        log INFO "Installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    else
        log INFO "Updating Homebrew"
        brew update
    fi

    brew install ${PACKAGES[@]}

fi

#################
# Cleanup
#################

log INFO "Bootstrap completed successfully!"
